# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read
  id-token: write

jobs:

  build:
    # Windows is currently the only platform this action supports
    runs-on: windows-latest

    steps:

      # Check-out repository
      - uses: actions/checkout@v3

      # Setup Python
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10' 
          architecture: 'x64' 
#          cache: 'pip'
#          cache-dependency-path: |
#            **/requirements*.txt

      - name: Compile kozmadeus-gui
        uses: Nuitka/Nuitka-Action@main
        with:
          nuitka-version: main
          script-name: test.py
          standalone: true
          onefile: false

      - name: Compile kozmadeus-cli
        uses: Nuitka/Nuitka-Action@main
        with:
          nuitka-version: main
          script-name: best.py
          standalone: true
          onefile: false

      - name: Move all dist files into general folder
        run: |
          mkdir build/artifact
          Move-Item -Force build/test.dist/* build/artifact
          Move-Item -Force build/best.dist/* build/artifact

      - uses: sigstore/gh-action-sigstore-python@v1.2.3
        with:
          inputs: ./build/artifact/*.exe

      # Uploads artifact
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: Windows Build
          path: build/artifact
